import { OutbreakGeoJSON } from "@/types";

// Static seed data for MVP — real outbreaks as of early 2026
// This replaces the Supabase backend until we connect it
export const seedOutbreaks: OutbreakGeoJSON = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [21.7587, -4.0383] },
      properties: {
        id: "1",
        outbreak_id: "ob-1",
        disease_name: "Mpox (Clade Ib)",
        severity: "critical",
        severity_score: 0.95,
        case_count: 48251,
        country: "DR Congo",
        region: "Eastern Provinces",
        status: "active",
        summary: "Ongoing mpox outbreak with sustained community transmission across eastern provinces.",
        reported_at: "2025-12-01T08:00:00Z",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [29.8739, -1.9403] },
      properties: {
        id: "2",
        outbreak_id: "ob-2",
        disease_name: "Mpox (Clade Ib)",
        severity: "severe",
        severity_score: 0.75,
        case_count: 3842,
        country: "Rwanda",
        region: null,
        status: "active",
        summary: "Cross-border mpox spread from DR Congo with local transmission chains.",
        reported_at: "2025-12-10T14:00:00Z",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [29.9189, -3.3731] },
      properties: {
        id: "3",
        outbreak_id: "ob-3",
        disease_name: "Mpox (Clade Ib)",
        severity: "severe",
        severity_score: 0.7,
        case_count: 2190,
        country: "Burundi",
        region: null,
        status: "active",
        summary: "Mpox cases increasing with community transmission.",
        reported_at: "2025-12-15T10:00:00Z",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [34.8888, 0.5176] },
      properties: {
        id: "4",
        outbreak_id: "ob-4",
        disease_name: "Mpox (Clade Ib)",
        severity: "moderate",
        severity_score: 0.5,
        case_count: 845,
        country: "Kenya",
        region: null,
        status: "active",
        summary: "Mpox cases detected with containment measures in place.",
        reported_at: "2025-12-22T06:00:00Z",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [32.2903, 1.3733] },
      properties: {
        id: "5",
        outbreak_id: "ob-5",
        disease_name: "Mpox (Clade Ib)",
        severity: "moderate",
        severity_score: 0.55,
        case_count: 1203,
        country: "Uganda",
        region: null,
        status: "active",
        summary: "Active mpox surveillance with sporadic community cases.",
        reported_at: "2025-12-28T12:00:00Z",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [47.5321, 2.0469] },
      properties: {
        id: "6",
        outbreak_id: "ob-6",
        disease_name: "Cholera",
        severity: "critical",
        severity_score: 0.9,
        case_count: 35000,
        country: "Somalia",
        region: "Banadir",
        status: "active",
        summary: "Severe cholera outbreak exacerbated by flooding and displacement.",
        reported_at: "2025-12-05T09:00:00Z",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [39.6682, 8.6268] },
      properties: {
        id: "7",
        outbreak_id: "ob-7",
        disease_name: "Cholera",
        severity: "severe",
        severity_score: 0.8,
        case_count: 22000,
        country: "Ethiopia",
        region: "Oromia",
        status: "active",
        summary: "Cholera outbreak spreading across multiple regions.",
        reported_at: "2025-12-12T16:00:00Z",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [90.3563, 23.685] },
      properties: {
        id: "8",
        outbreak_id: "ob-8",
        disease_name: "Dengue",
        severity: "severe",
        severity_score: 0.72,
        case_count: 65000,
        country: "Bangladesh",
        region: "Dhaka Division",
        status: "active",
        summary: "Record dengue season with healthcare system under significant strain.",
        reported_at: "2026-01-03T08:00:00Z",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-43.1729, -22.9068] },
      properties: {
        id: "9",
        outbreak_id: "ob-9",
        disease_name: "Dengue",
        severity: "severe",
        severity_score: 0.78,
        case_count: 980000,
        country: "Brazil",
        region: "Rio de Janeiro",
        status: "active",
        summary: "Major dengue epidemic with emergency measures declared in multiple states.",
        reported_at: "2026-01-08T11:00:00Z",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-99.1332, 19.4326] },
      properties: {
        id: "10",
        outbreak_id: "ob-10",
        disease_name: "Dengue",
        severity: "moderate",
        severity_score: 0.55,
        case_count: 42000,
        country: "Mexico",
        region: "Multiple States",
        status: "active",
        summary: "Elevated dengue activity across southern and coastal states.",
        reported_at: "2026-01-10T15:00:00Z",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [44.2075, 15.3694] },
      properties: {
        id: "11",
        outbreak_id: "ob-11",
        disease_name: "Cholera",
        severity: "critical",
        severity_score: 0.88,
        case_count: 28000,
        country: "Yemen",
        region: null,
        status: "active",
        summary: "Protracted cholera crisis with ongoing transmission in conflict-affected areas.",
        reported_at: "2025-12-18T07:00:00Z",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [53.688, 32.4279] },
      properties: {
        id: "12",
        outbreak_id: "ob-12",
        disease_name: "Measles",
        severity: "severe",
        severity_score: 0.65,
        case_count: 15200,
        country: "Iran",
        region: null,
        status: "active",
        summary: "Measles resurgence driven by vaccination gaps in border provinces.",
        reported_at: "2026-01-05T13:00:00Z",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [69.1761, 34.5553] },
      properties: {
        id: "13",
        outbreak_id: "ob-13",
        disease_name: "Measles",
        severity: "critical",
        severity_score: 0.85,
        case_count: 42300,
        country: "Afghanistan",
        region: "Multiple Provinces",
        status: "active",
        summary: "Widespread measles outbreak affecting children under 5 with limited vaccine access.",
        reported_at: "2025-12-20T10:00:00Z",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [67.0011, 30.3753] },
      properties: {
        id: "14",
        outbreak_id: "ob-14",
        disease_name: "Polio (cVDPV2)",
        severity: "severe",
        severity_score: 0.7,
        case_count: 125,
        country: "Pakistan",
        region: "Balochistan / KPK",
        status: "active",
        summary: "Circulating vaccine-derived poliovirus with environmental detections.",
        reported_at: "2026-01-12T09:00:00Z",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [34.3088, 31.3547] },
      properties: {
        id: "15",
        outbreak_id: "ob-15",
        disease_name: "Polio (cVDPV2)",
        severity: "severe",
        severity_score: 0.72,
        case_count: 89,
        country: "Palestine",
        region: "Gaza",
        status: "active",
        summary: "Poliovirus detected amid disrupted healthcare infrastructure.",
        reported_at: "2026-01-15T14:00:00Z",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [104.1954, 35.8617] },
      properties: {
        id: "16",
        outbreak_id: "ob-16",
        disease_name: "H5N1 Avian Influenza",
        severity: "moderate",
        severity_score: 0.45,
        case_count: 18,
        country: "China",
        region: "Multiple Provinces",
        status: "monitoring",
        summary: "Sporadic human H5N1 cases linked to poultry exposure. Monitoring for sustained transmission.",
        reported_at: "2026-01-18T08:00:00Z",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-95.7129, 37.0902] },
      properties: {
        id: "17",
        outbreak_id: "ob-17",
        disease_name: "H5N1 Avian Influenza",
        severity: "moderate",
        severity_score: 0.48,
        case_count: 72,
        country: "United States",
        region: "Multiple States",
        status: "active",
        summary: "H5N1 detected in dairy cattle herds with sporadic human cases among farm workers.",
        reported_at: "2026-01-20T16:00:00Z",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [33.4297, -0.0236] },
      properties: {
        id: "18",
        outbreak_id: "ob-18",
        disease_name: "Ebola (Sudan)",
        severity: "severe",
        severity_score: 0.82,
        case_count: 216,
        country: "Uganda",
        region: "Central Region",
        status: "active",
        summary: "Sudan ebolavirus outbreak with active case finding and contact tracing.",
        reported_at: "2026-01-22T11:00:00Z",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-72.2852, 18.9712] },
      properties: {
        id: "19",
        outbreak_id: "ob-19",
        disease_name: "Cholera",
        severity: "severe",
        severity_score: 0.68,
        case_count: 18500,
        country: "Haiti",
        region: null,
        status: "active",
        summary: "Ongoing cholera transmission amid water and sanitation infrastructure challenges.",
        reported_at: "2026-01-25T07:00:00Z",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [100.9925, 15.87] },
      properties: {
        id: "20",
        outbreak_id: "ob-20",
        disease_name: "Dengue",
        severity: "moderate",
        severity_score: 0.52,
        case_count: 38000,
        country: "Thailand",
        region: null,
        status: "active",
        summary: "Above-average dengue season with focus on vector control measures.",
        reported_at: "2026-01-27T13:00:00Z",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [25.0136, -8.8383] },
      properties: {
        id: "21",
        outbreak_id: "ob-21",
        disease_name: "Malaria",
        severity: "severe",
        severity_score: 0.76,
        case_count: 2100000,
        country: "DR Congo",
        region: "Multiple Provinces",
        status: "active",
        summary: "Endemic malaria with seasonal surge exceeding response capacity.",
        reported_at: "2025-12-08T10:00:00Z",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [7.4898, 9.0579] },
      properties: {
        id: "22",
        outbreak_id: "ob-22",
        disease_name: "Diphtheria",
        severity: "moderate",
        severity_score: 0.52,
        case_count: 4200,
        country: "Nigeria",
        region: "Northern States",
        status: "active",
        summary: "Diphtheria outbreak in states with low routine immunization coverage.",
        reported_at: "2026-01-28T15:00:00Z",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [45.0382, 2.0469] },
      properties: {
        id: "23",
        outbreak_id: "ob-23",
        disease_name: "Measles",
        severity: "severe",
        severity_score: 0.71,
        case_count: 19800,
        country: "Somalia",
        region: null,
        status: "active",
        summary: "Large measles outbreak among displaced populations with limited healthcare access.",
        reported_at: "2026-01-30T09:00:00Z",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [106.8456, -6.2088] },
      properties: {
        id: "24",
        outbreak_id: "ob-24",
        disease_name: "Dengue",
        severity: "moderate",
        severity_score: 0.58,
        case_count: 95000,
        country: "Indonesia",
        region: "Java",
        status: "active",
        summary: "Dengue cases rising with onset of rainy season across Java and Sumatra.",
        reported_at: "2026-02-01T06:00:00Z",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [36.8219, -1.2921] },
      properties: {
        id: "25",
        outbreak_id: "ob-25",
        disease_name: "Marburg Virus",
        severity: "severe",
        severity_score: 0.8,
        case_count: 64,
        country: "Kenya",
        region: "Western Kenya",
        status: "active",
        summary: "Marburg virus outbreak with active surveillance at borders.",
        reported_at: "2026-02-01T14:00:00Z",
      },
    },
  ],
};

// Feed items for the news panel
export interface FeedItem {
  id: string;
  outbreak_id: string;
  source_type: "who" | "cdc" | "news" | "user";
  source_name: string;
  disease_name: string;
  title: string;
  location: string;
  published_at: string;
  severity: "low" | "moderate" | "severe" | "critical";
}

export const seedFeedItems: FeedItem[] = [
  {
    id: "f1",
    outbreak_id: "ob-1",
    source_type: "who",
    source_name: "WHO",
    disease_name: "Mpox (Clade Ib)",
    title: "Mpox multi-country outbreak — Situation update",
    location: "DR Congo",
    published_at: "2026-02-01T08:00:00Z",
    severity: "critical",
  },
  {
    id: "f2",
    outbreak_id: "ob-6",
    source_type: "who",
    source_name: "WHO",
    disease_name: "Cholera",
    title: "Cholera situation in Somalia — Emergency response scaled up",
    location: "Somalia",
    published_at: "2026-02-01T06:30:00Z",
    severity: "critical",
  },
  {
    id: "f3",
    outbreak_id: "ob-9",
    source_type: "news",
    source_name: "Reuters",
    disease_name: "Dengue",
    title: "Brazil declares emergency in three states as dengue cases surge",
    location: "Brazil",
    published_at: "2026-02-01T04:15:00Z",
    severity: "severe",
  },
  {
    id: "f4",
    outbreak_id: "ob-17",
    source_type: "cdc",
    source_name: "CDC",
    disease_name: "H5N1 Avian Influenza",
    title: "H5N1 bird flu — Updated case count and dairy herd monitoring",
    location: "United States",
    published_at: "2026-01-31T22:00:00Z",
    severity: "moderate",
  },
  {
    id: "f5",
    outbreak_id: "ob-18",
    source_type: "who",
    source_name: "WHO",
    disease_name: "Ebola (Sudan)",
    title: "Sudan ebolavirus disease — Uganda situation report #14",
    location: "Uganda",
    published_at: "2026-01-31T18:45:00Z",
    severity: "severe",
  },
  {
    id: "f6",
    outbreak_id: "ob-13",
    source_type: "who",
    source_name: "WHO",
    disease_name: "Measles",
    title: "Measles vaccination campaign reaches 2.1M children in Afghanistan",
    location: "Afghanistan",
    published_at: "2026-01-31T14:00:00Z",
    severity: "critical",
  },
  {
    id: "f7",
    outbreak_id: "ob-25",
    source_type: "news",
    source_name: "BBC",
    disease_name: "Marburg Virus",
    title: "Kenya strengthens border screening as Marburg cases confirmed",
    location: "Kenya",
    published_at: "2026-01-31T11:20:00Z",
    severity: "severe",
  },
  {
    id: "f8",
    outbreak_id: "ob-15",
    source_type: "who",
    source_name: "WHO",
    disease_name: "Polio (cVDPV2)",
    title: "Polio vaccination round completed in Gaza amid ongoing challenges",
    location: "Palestine",
    published_at: "2026-01-31T09:00:00Z",
    severity: "severe",
  },
  {
    id: "f9",
    outbreak_id: "ob-8",
    source_type: "news",
    source_name: "Al Jazeera",
    disease_name: "Dengue",
    title: "Bangladesh hospitals overwhelmed as dengue cases hit new record",
    location: "Bangladesh",
    published_at: "2026-01-30T20:30:00Z",
    severity: "severe",
  },
  {
    id: "f10",
    outbreak_id: "ob-19",
    source_type: "news",
    source_name: "AP News",
    disease_name: "Cholera",
    title: "Haiti cholera response hampered by security situation",
    location: "Haiti",
    published_at: "2026-01-30T16:00:00Z",
    severity: "severe",
  },
];
